//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Id_Partners { get; set; }
        public Nullable<int> TypePartners { get; set; }
        public string NameCompany { get; set; }
        public string LegalAdress { get; set; }
        public string INN { get; set; }
        public string FIO_Directed { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> Rating { get; set; }
        public string PlaceOfSales { get; set; }
    
        public virtual TypePartners TypePartners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
