//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id_Ticket { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public Nullable<int> SumTickets { get; set; }
        public Nullable<int> Ammount { get; set; }
        public Nullable<int> Id_Partners { get; set; }
        public Nullable<System.DateTime> DateOfComplete { get; set; }
        public Nullable<int> Id_StatusTickets { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Product Product { get; set; }
        public virtual StatusTickets StatusTickets { get; set; }
    }
}
